export interface Customer {
    customer_number: string,
    account_id: string,
    account_start_date: string,
    client_district_code: string,
    client_group: string,
    client_id: string,
    client_name: string,
    client_office_code: string,
    company_code: string,
    customer_company_name: string,
    data_source: string,
    industry: string,
    industry_code_text: string,
    master_client_id: string,
    master_client_name: string,
    mc_division: string,
    mc_group: string,
    mc_office: string,
    sales_district_code: string,
    sales_group: string,
    sales_office: string,
    industry_client_id: string,
    industry_code_txt_client_id: string,
    customer_hierarchy_id: string,
    create_datetime: string,
    update_datetime: string,
}