export const terminalRouteMaster = [
  {
    id: 1,
    terminalNumber: "T1",
    routeNumber: "541 SP2",
    province: "BC",
    year: 2023,
    fuelType: "Gasoline",
    terminalRouteAveragePeak: 19.83,
    terminalRouteAverageNonPeak: 17.92,
    terminalAveragePeak: 16.85,
    terminalAverageNonPeak: 14.92,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-19",
    terminalRouteFuelTypeAverages: [
      {
        id: 101,
        terminalRouteMasterId: 1,
        fuelType: "Gasoline",
        fuelTypeTotalPeak: 348.8,
        fuelTypeTotalNonPeak: 287.36,
        totalDaysPeak: 16,
        totalDaysNonPeak: 16,
        terminalRouteAveragePeak: 21.8,
        terminalRouteAverageNonPeak: 17.96,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      },
      {
        id: 102,
        terminalRouteMasterId: 1,
        fuelType: "Diesel",
        fuelTypeTotalPeak: 412.5,
        fuelTypeTotalNonPeak: 345.2,
        totalDaysPeak: 18,
        totalDaysNonPeak: 19,
        terminalRouteAveragePeak: 22.92,
        terminalRouteAverageNonPeak: 18.17,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: true,
        reasonForChange: "invalid entry",
        active: true
      },
      {
        id: 103,
        terminalRouteMasterId: 1,
        fuelType: "Electric",
        fuelTypeTotalPeak: 785.4,
        fuelTypeTotalNonPeak: 412.3,
        totalDaysPeak: 12,
        totalDaysNonPeak: 14,
        terminalRouteAveragePeak: 65.45,
        terminalRouteAverageNonPeak: 29.45,
        unitOfMeasure: "kWh",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      }
    ]
  },
  {
    id: 2,
    terminalNumber: "T2",
    routeNumber: "541 SP2",
    province: "BC",
    year: 2023,
    fuelType: "Electric",
    terminalRouteAveragePeak: 54.2,
    terminalRouteAverageNonPeak: 34.5,
    terminalAveragePeak: 16.85,
    terminalAverageNonPeak: 14.92,
    unitOfMeasure: "kWh",
    createdBy: "sadmin",
    createdDate: "2025-03-19",
    terminalRouteFuelTypeAverages: [
      {
        id: 201,
        terminalRouteMasterId: 2,
        fuelType: "Electric",
        fuelTypeTotalPeak: 650.4,
        fuelTypeTotalNonPeak: 483.0,
        totalDaysPeak: 10,
        totalDaysNonPeak: 14,
        terminalRouteAveragePeak: 65.04,
        terminalRouteAverageNonPeak: 34.5,
        unitOfMeasure: "kWh",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      },
      {
        id: 202,
        terminalRouteMasterId: 2,
        fuelType: "Hybrid",
        fuelTypeTotalPeak: 312.5,
        fuelTypeTotalNonPeak: 287.3,
        totalDaysPeak: 15,
        totalDaysNonPeak: 16,
        terminalRouteAveragePeak: 20.83,
        terminalRouteAverageNonPeak: 17.96,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      }
    ]
  },
  {
    id: 3,
    terminalNumber: "T4",
    routeNumber: "060 A81",
    province: "ON",
    year: 2023,
    fuelType: "Gasoline",
    terminalRouteAveragePeak: 21.63,
    terminalRouteAverageNonPeak: 19.92,
    terminalAveragePeak: 20.15,
    terminalAverageNonPeak: 18.87,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-19",
    terminalRouteFuelTypeAverages: [
      {
        id: 401,
        terminalRouteMasterId: 4,
        fuelType: "Gasoline",
        fuelTypeTotalPeak: 432.6,
        fuelTypeTotalNonPeak: 398.4,
        totalDaysPeak: 20,
        totalDaysNonPeak: 20,
        terminalRouteAveragePeak: 21.63,
        terminalRouteAverageNonPeak: 19.92,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      }
    ]
  },
  {
    id: 4,
    terminalNumber: "T5",
    routeNumber: "060 BC2",
    province: "ON",
    year: 2023,
    fuelType: "Electric",
    terminalRouteAveragePeak: 63.2,
    terminalRouteAverageNonPeak: 41.5,
    terminalAveragePeak: 58.7,
    terminalAverageNonPeak: 39.2,
    unitOfMeasure: "kWh",
    createdBy: "sadmin",
    createdDate: "2025-03-19",
    terminalRouteFuelTypeAverages: []
  },
  {
    id: 5,
    terminalNumber: "T6",
    routeNumber: "541 SP2",
    province: "BC",
    year: 2023,
    fuelType: "Gasoline",
    terminalRouteAveragePeak: 19.83,
    terminalRouteAverageNonPeak: 17.92,
    terminalAveragePeak: 16.85,
    terminalAverageNonPeak: 14.92,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-19",
    terminalRouteFuelTypeAverages: [
      {
        id: 301,
        terminalRouteMasterId: 5,
        fuelType: "Gasoline",
        fuelTypeTotalPeak: 348.8,
        fuelTypeTotalNonPeak: 287.36,
        totalDaysPeak: 16,
        totalDaysNonPeak: 16,
        terminalRouteAveragePeak: 21.8,
        terminalRouteAverageNonPeak: 17.96,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      },
      {
        id: 302,
        terminalRouteMasterId: 5,
        fuelType: "Diesel",
        fuelTypeTotalPeak: 412.5,
        fuelTypeTotalNonPeak: 345.2,
        totalDaysPeak: 18,
        totalDaysNonPeak: 19,
        terminalRouteAveragePeak: 22.92,
        terminalRouteAverageNonPeak: 18.17,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      },
    ]
  },
  {
    id: 6,
    terminalNumber: "T8",
    routeNumber: "603 E14",
    province: "BC",
    year: 2023,
    fuelType: "Gasoline",
    terminalRouteAveragePeak: 22.4,
    terminalRouteAverageNonPeak: 19.3,
    terminalAveragePeak: 20.7,
    terminalAverageNonPeak: 17.8,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-20",
    terminalRouteFuelTypeAverages: []
  },
  {
    id: 7,
    terminalNumber: "T9",
    routeNumber: "604 F15",
    province: "ON",
    year: 2022,
    fuelType: "Hybrid",
    terminalRouteAveragePeak: 28.6,
    terminalRouteAverageNonPeak: 23.4,
    terminalAveragePeak: 26.1,
    terminalAverageNonPeak: 21.9,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-20",
    terminalRouteFuelTypeAverages: []
  },
  {
    id: 8,
    terminalNumber: "T10",
    routeNumber: "605 G16",
    province: "AB",
    year: 2024,
    fuelType: "Diesel",
    terminalRouteAveragePeak: 35.1,
    terminalRouteAverageNonPeak: 29.7,
    terminalAveragePeak: 32.8,
    terminalAverageNonPeak: 27.4,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-20",
    terminalRouteFuelTypeAverages: [
      {
        id: 1201,
        terminalRouteMasterId: 2,
        fuelType: "Electric",
        fuelTypeTotalPeak: 650.4,
        fuelTypeTotalNonPeak: 483.0,
        totalDaysPeak: 10,
        totalDaysNonPeak: 14,
        terminalRouteAveragePeak: 65.04,
        terminalRouteAverageNonPeak: 34.5,
        unitOfMeasure: "kWh",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      },
      {
        id: 1202,
        terminalRouteMasterId: 2,
        fuelType: "Hybrid",
        fuelTypeTotalPeak: 312.5,
        fuelTypeTotalNonPeak: 287.3,
        totalDaysPeak: 15,
        totalDaysNonPeak: 16,
        terminalRouteAveragePeak: 20.83,
        terminalRouteAverageNonPeak: 17.96,
        unitOfMeasure: "litres",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      }
    ]
  },
  {
    id: 9,
    terminalNumber: "T11",
    routeNumber: "606 H17",
    province: "QC",
    year: 2022,
    fuelType: "Electric",
    terminalRouteAveragePeak: 58.3,
    terminalRouteAverageNonPeak: 42.1,
    terminalAveragePeak: 54.2,
    terminalAverageNonPeak: 39.5,
    unitOfMeasure: "kWh",
    createdBy: "sadmin",
    createdDate: "2025-03-20",
    terminalRouteFuelTypeAverages: []
  },
  {
    id: 10,
    terminalNumber: "T12",
    routeNumber: "607 I18",
    province: "MB",
    year: 2024,
    fuelType: "Gasoline",
    terminalRouteAveragePeak: 23.7,
    terminalRouteAverageNonPeak: 20.1,
    terminalAveragePeak: 21.5,
    terminalAverageNonPeak: 18.9,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-21",
    terminalRouteFuelTypeAverages: []
  },
  {
    id: 11,
    terminalNumber: "T13",
    routeNumber: "608 J19",
    province: "BC",
    year: 2022,
    fuelType: "Diesel",
    terminalRouteAveragePeak: 31.9,
    terminalRouteAverageNonPeak: 26.7,
    terminalAveragePeak: 29.4,
    terminalAverageNonPeak: 24.8,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-21",
    terminalRouteFuelTypeAverages: []
  },
  {
    id: 12,
    terminalNumber: "T14",
    routeNumber: "609 K20",
    province: "ON",
    year: 2024,
    fuelType: "Hybrid",
    terminalRouteAveragePeak: 27.5,
    terminalRouteAverageNonPeak: 22.2,
    terminalAveragePeak: 25.3,
    terminalAverageNonPeak: 20.1,
    unitOfMeasure: "litres",
    createdBy: "sadmin",
    createdDate: "2025-03-21",
    terminalRouteFuelTypeAverages: [
      {
        id: 901,
        terminalRouteMasterId: 14,
        fuelType: "Electric",
        fuelTypeTotalPeak: 650.4,
        fuelTypeTotalNonPeak: 483.0,
        totalDaysPeak: 10,
        totalDaysNonPeak: 14,
        terminalRouteAveragePeak: 65.04,
        terminalRouteAverageNonPeak: 34.5,
        unitOfMeasure: "kWh",
        createdBy: "sadmin",
        createdDate: "2025-03-19",
        override: false,
        reasonForChange: "",
        active: true
      },
    ]
  },
];


export const terminalRouteVehicleAverages = [
  {
    "timecard_date": "2023-01-02",
    "terminal_id": 1001,
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-02",
    "total_fuel_adjusted": 18.42,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 1,
    "asset_number": "216112020",
    "terminalRouteFuelTypeAverageId": 101
  },
  {
    "terminal_id": 1002,
    "timecard_date": "2023-01-03",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-03",
    "total_fuel_adjusted": 19.61,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 2,
    "asset_number": "216112030",
    "terminalRouteFuelTypeAverageId": 101,
  },
  {
    "terminal_id": 1003,
    "timecard_date": "2023-01-04",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-04",
    "total_fuel_adjusted": 20.15,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 3,
    "asset_number": "216112040",
    "terminalRouteFuelTypeAverageId": 101,
  },
  {
    "terminal_id": 7001,
    "timecard_date": "2023-01-02",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-02",
    "total_fuel_adjusted": 18.42,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 4,
    "asset_number": "216112020",
    "terminalRouteFuelTypeAverageId": 101,
  },
  {
    "terminal_id": 5002,
    "timecard_date": "2023-01-03",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-03",
    "total_fuel_adjusted": 19.61,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 5,
    "asset_number": "216112030",
    "terminalRouteFuelTypeAverageId": 101,
  },
  {
    "terminal_id": 10056,
    "timecard_date": "2023-01-04",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-04",
    "total_fuel_adjusted": 20.15,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 6,
    "asset_number": "216112040",
    "terminalRouteFuelTypeAverageId": 101,
  },
  {
    "terminal_id": 1004,
    "timecard_date": "2023-01-05",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-05",
    "total_fuel_adjusted": 22.37,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 7,
    "asset_number": "216112050",
    "terminalRouteFuelTypeAverageId": 102,
  },
  {
    "terminal_id": 1005,
    "timecard_date": "2023-01-06",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-06",
    "total_fuel_adjusted": 21.85,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 8,
    "asset_number": "216112060",
    "terminalRouteFuelTypeAverageId": 102,
  },
  {
    "terminal_id": 1006,
    "timecard_date": "2023-01-09",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-09",
    "total_fuel_adjusted": 19.92,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 9,
    "asset_number": "216112070",
    "terminalRouteFuelTypeAverageId": 102,
  },
  {
    "terminal_id": 1007,
    "timecard_date": "2023-01-10",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-10",
    "total_fuel_adjusted": 23.15,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 10,
    "asset_number": "216112080",
    "terminalRouteFuelTypeAverageId": 103,
  },
  {
    "terminal_id": 1008,
    "timecard_date": "2023-01-11",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-11",
    "total_fuel_adjusted": 20.67,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 11,
    "asset_number": "216112090",
    "terminalRouteFuelTypeAverageId": 201,
  },
  {
    "terminal_id": 1009,
    "timecard_date": "2023-01-12",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-12",
    "total_fuel_adjusted": 18.95,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 12,
    "asset_number": "216112100",
    "terminalRouteFuelTypeAverageId": 301,
  },
  {
    "terminal_id": 1010,
    "timecard_date": "2023-01-13",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Gasoline",
    "trip_date": "2023-01-13",
    "total_fuel_adjusted": 19.42,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 13,
    "asset_number": "216112110",
    "terminalRouteFuelTypeAverageId": 301,
  },

  {
    "terminal_id": 1101,
    "timecard_date": "2023-01-02",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Diesel",
    "trip_date": "2023-01-02",
    "total_fuel_adjusted": 22.15,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 14,
    "asset_number": "216113020",
    "terminalRouteFuelTypeAverageId": 102
  },
  {
    "terminal_id": 1102,
    "timecard_date": "2023-01-03",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Diesel",
    "trip_date": "2023-01-03",
    "total_fuel_adjusted": 23.76,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 15,
    "asset_number": "216113030",
    "terminalRouteFuelTypeAverageId": 102,
  },
  {
    "terminal_id": 1103,
    "timecard_date": "2023-01-04",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Diesel",
    "trip_date": "2023-01-04",
    "total_fuel_adjusted": 21.89,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 16,
    "asset_number": "216113040",
    "terminalRouteFuelTypeAverageId": 102,
  },
  {
    "terminal_id": 1104,
    "timecard_date": "2023-01-05",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Diesel",
    "trip_date": "2023-01-05",
    "total_fuel_adjusted": 24.12,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 17,
    "asset_number": "216113050",
    "terminalRouteFuelTypeAverageId": 102,
  },
  {
    "terminal_id": 1105,
    "timecard_date": "2023-01-06",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Diesel",
    "trip_date": "2023-01-06",
    "total_fuel_adjusted": 20.45,
    "energy_used_kwh": null,
    "skip_calculation": false,
    "vehicle_id": 18,
    "asset_number": "216113060",
    "terminalRouteFuelTypeAverageId": 102,
  },

  {
    "terminal_id": 1201,
    "timecard_date": "2023-01-02",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-02",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 62.5,
    "skip_calculation": false,
    "vehicle_id": 19,
    "asset_number": "216114020",
    "terminalRouteFuelTypeAverageId": 301,
  },
  {
    "terminal_id": 1202,
    "timecard_date": "2023-01-03",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-03",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 68.7,
    "skip_calculation": false,
    "vehicle_id": 20,
    "asset_number": "216114030",
    "terminalRouteFuelTypeAverageId": 301,
  },
  {
    "terminal_id": 1203,
    "timecard_date": "2023-01-04",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-04",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 65.2,
    "skip_calculation": false,
    "vehicle_id": 21,
    "asset_number": "216114040",
    "terminalRouteFuelTypeAverageId": 301,
  },
  {
    "terminal_id": 1204,
    "timecard_date": "2023-01-05",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-05",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 70.1,
    "skip_calculation": false,
    "vehicle_id": 22,
    "asset_number": "216114050",
    "terminalRouteFuelTypeAverageId": 301,
  },
  {
    "terminal_id": 1205,
    "timecard_date": "2023-01-06",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-06",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 63.8,
    "skip_calculation": false,
    "vehicle_id": 23,
    "asset_number": "216114060",
    "terminalRouteFuelTypeAverageId": 301,
  },

  {
    "terminal_id": 2001,
    "timecard_date": "2023-01-02",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-02",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 64.2,
    "skip_calculation": false,
    "vehicle_id": 24,
    "asset_number": "216115020",
    "terminalRouteFuelTypeAverageId": 401,
  },
  {
    "terminal_id": 2002,
    "timecard_date": "2023-01-03",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-03",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 66.5,
    "skip_calculation": false,
    "vehicle_id": 25,
    "asset_number": "216115030",
    "terminalRouteFuelTypeAverageId": 401,
  },
  {
    "terminal_id": 2003,
    "timecard_date": "2023-01-04",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-04",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 62.1,
    "skip_calculation": false,
    "vehicle_id": 26,
    "asset_number": "216115040",
    "terminalRouteFuelTypeAverageId": 301,
  },
  {
    "terminal_id": 2004,
    "timecard_date": "2023-01-05",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-05",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 68.9,
    "skip_calculation": false,
    "vehicle_id": 27,
    "asset_number": "216115050",
    "terminalRouteFuelTypeAverageId": 401,
  },
  {
    "terminal_id": 2005,
    "timecard_date": "2023-01-06",
    "route_number": "541 1922",
    "pcl_agent_flag": "Y",
    "primary_fuel_type": "Electric",
    "trip_date": "2023-01-06",
    "total_fuel_adjusted": null,
    "energy_used_kwh": 65.7,
    "skip_calculation": false,
    "vehicle_id": 28,
    "asset_number": "216115060",
    "terminalRouteFuelTypeAverageId": 401,
  }
];
